apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant
  name: example-tenant-ns
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: example-collector
spec:
  debug: true
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: example-collector
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: example-collector
  name: example-tenant
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant
  logSourceNamespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: logging
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-1
  namespace: example-tenant-ns
spec:
  condition: "true"
  outputs:
    - name: file-test-output-1
      namespace: example-tenant-ns
    - name: file-test-output-2
      namespace: example-tenant-ns
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: file-test-output-1
  namespace: example-tenant-ns
spec:
  file:
    path: "/file-exporter/logs.json"
    append: true
    format: "json"
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: file-test-output-2
  namespace: example-tenant-ns
spec:
  file:
    path: "/file-exporter/logs-2.json"
    append: true
    format: "json"
