apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: example-tenant-ns
  annotations:
    telemetry.kube-logging.dev/exclude: "true"
spec:
  containers:
  - name: hello-container
    image: busybox
    command: ["sh", "-c", "while true; do echo hello; sleep 1; done"]
