apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: receiver
  namespace: example-tenant-ns
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
    service:
        pipelines:
          logs: 
            receivers: [otlp]
            exporters: [debug]
