apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant-1
  name: example-tenant-ns-1
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nsSelector: example-tenant-2
  name: example-tenant-ns-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: example-collector-1
spec:
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: example-collector-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: example-collector-2
spec:
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: example-collector-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: example-collector-1
  name: example-tenant-1
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
  logSourceNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: example-collector-2
  name: example-tenant-2
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-2
  logSourceNamespaceSelectors:
    - matchLabels:
        nsSelector: example-tenant-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-1
  namespace: example-tenant-ns-1
spec:
  condition: "true"
  outputs:
    - name: otlp-test-output-1
      namespace: example-tenant-ns-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: subscription-sample-2
  namespace: example-tenant-ns-2
spec:
  condition: "true"
  outputs:
    - name: otlp-test-output-2
      namespace: example-tenant-ns-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: otlp-test-output-1
  namespace: example-tenant-ns-1
spec:
  otlp:
    endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
    tls:
      insecure: true
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: otlp-test-output-2
  namespace: example-tenant-ns-2
spec:
  otlp:
    endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
    tls:
      insecure: true
