apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-receiver-web
  namespace: web
spec:
  managementState: managed
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.112.0
  volumeMounts:
    - name: export-web
      mountPath: /etc/otelcol-contrib/
  volumes:
    - name: export-web
      hostPath:
        path: /etc/otelcol-contrib/
        type: DirectoryOrCreate
  initContainers:
    - name: init-chmod
      image: busybox
      command: ["sh", "-c"]
      args: ["chmod -R 777 /etc/otelcol-contrib/"]
      volumeMounts:
        - name: export-web
          mountPath: /etc/otelcol-contrib/
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      file/direct:
        path: /etc/otelcol-contrib/export-web.log
        append: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [file/direct]
