apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: openobserve
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: shared
  name: shared
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: database
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: web
  name: web
