apiVersion: v1
kind: Service
metadata:
  name: openobserve-otlp-grpc
  namespace: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
    - name: otlp-grpc
      port: 5081
      targetPort: 5081
