# permissions for end users to view tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: telemetry-tenant-viewer-role
rules:
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - tenants/status
  verbs:
  - get
