# permissions for end users to edit collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: telemetry-collector-editor-role
rules:
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - collectors/status
  verbs:
  - get
