# permissions for end users to view outputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: output-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: telemetry-controller
    app.kubernetes.io/part-of: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: output-viewer-role
rules:
  - apiGroups:
      - telemetry.kube-logging.dev
    resources:
      - outputs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - telemetry.kube-logging.dev
    resources:
      - outputs/status
    verbs:
      - get
