# permissions for end users to view bridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: telemetry-bridge-viewer-role
rules:
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - bridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.kube-logging.dev
  resources:
  - bridges/status
  verbs:
  - get
