apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: loki-1
  name: tenant-loki-1
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: loki-2
  name: tenant-loki-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: kubernetes
spec:
  #debug: true
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: kubernetes
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: kubernetes
  name: loki-1
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: loki-1
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: loki-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: all-logs
  namespace: tenant-loki-1
spec:
  ottl: 'route()'
  outputs:
    - name: loki
      namespace: collector
    - name: openobserve-1
      namespace: collector
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: OtelOutput
metadata:
  name: loki
  namespace: collector
spec:
  loki:
    endpoint: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
    tls:
      insecure: true
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: kubernetes
  name: loki-2
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: loki-2
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: loki-2
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: all-logs
  namespace: tenant-loki-2
spec:
  ottl: 'route()'
  outputs:
    - name: loki
      namespace: collector
    - name: openobserve-2
      namespace: collector
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: OtelOutput
metadata:
  name: openobserve-1
  namespace: collector
spec:
  otlp:
    endpoint: openobserve-otlp-grpc.openobserve.svc.cluster.local:5081
    headers:
      Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTpKSng2UmcxQ09zVmJFaWs3"
      organization: loki-1
      stream-name: all-logs
    tls:
      insecure: true
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: OtelOutput
metadata:
  name: openobserve-2
  namespace: collector
spec:
  otlp:
    endpoint: openobserve-otlp-grpc.openobserve.svc.cluster.local:5081
    headers:
      Authorization: "Basic cm9vdEBleGFtcGxlLmNvbTpKSng2UmcxQ09zVmJFaWs3"
      organization: loki-2
      stream-name: all-logs
    tls:
      insecure: true
