apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: demo-1
  name: tenant-demo-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: kubernetes
spec:
  debug: true
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: kubernetes
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: kubernetes
  name: demo-1
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: demo-1
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: demo-1
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: all-logs
  namespace: tenant-demo-1
spec:
  debug: true
  ottl: 'route()'
  outputs:
    - name: fluent
      namespace: collector
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: OtelOutput
metadata:
  name: fluent
  namespace: collector
spec:
  fluentforward:
    endpoint: all-to-file-fluentd.default:24240
    tag: asd
