## Append samples of your project ##
resources:
- telemetry_v1alpha1_collector.yaml
- telemetry_v1alpha1_subscription.yaml
- telemetry_v1alpha1_tenant.yaml
- telemetry_v1alpha1_oteloutput.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
