apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test-otlp-receiver-1
  namespace: otlp-receiver-1
  labels:
    test-otlp-receiver: test
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 1

    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
          level: detailed
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [debug]
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test-otlp-receiver-2
  namespace: otlp-receiver-2
  labels:
    test-otlp-receiver: test
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 1

    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
          level: detailed
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [debug]