apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/instance: subscription-sample
    app.kubernetes.io/part-of: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-controller
  name: subscription-sample
spec:
  outputs:
    - name: output-sample
      namespace: collector
