apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/instance: collector-sample
    app.kubernetes.io/part-of: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-controller
  name: collector-sample
spec:
  tenantSelector:
    matchLabels:
      tenant: tenantA
