apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Bridge
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: bridge-sample
spec:
  sourceTenant: shared
  destinationTenant: tenantA
  condition: 'attributes["parsed"]["method"] == "GET"'
