apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: output-sample
spec:
  otlp:
    endpoint: receiver.svc.cluster.local:4317
    tls:
      insecure: true
