apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: subscription-sample
spec:
  condition: "true"
  outputs:
    - name: output-sample
      namespace: collector
