apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: collector-sample
spec:
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      tenant: tenantA
