apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/name: subscription
    app.kubernetes.io/instance: subscription-sample
    app.kubernetes.io/part-of: subscription-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: subscription-operator
  name: subscription-sample
spec:
  outputs:
    - name: oteloutput-sample
      namespace: collector
