apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: tenant
    app.kubernetes.io/instance: tenant-sample
    app.kubernetes.io/part-of: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-controller
    tenant: tenantA
  name: tenant-sample
spec:
  subscriptionNamespaceSelector:
    matchLabels:
      nsTenant: tenantA
