apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: telemetry-controller
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  subscriptionNamespaceSelector:
    matchLabels:
      nsTenant: tenantA
  logSourceNamespaceSelector:
    matchLabels:
      nsTenant: tenantA
