apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    nsSelector: tenant-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    nsSelector: tenant-db
