receivers:
    filelog/kubernetes:
        exclude:
            - /var/log/pods/*/otc-container/*.log
        include:
            - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
            - id: get-format
              routes:
                - expr: body matches "^\\{"
                  output: parser-docker
                - expr: body matches "^[^ Z]+Z"
                  output: parser-containerd
              type: router
            - id: parser-containerd
              output: extract_metadata_from_filepath
              regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
              timestamp:
                layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                parse_from: attributes.time
              type: regex_parser
            - id: parser-docker
              output: extract_metadata_from_filepath
              timestamp:
                layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                parse_from: attributes.time
              type: json_parser
            - cache:
                size: 128
              id: extract_metadata_from_filepath
              parse_from: attributes["log.file.path"]
              regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9-]+)\/(?P<container_name>[^\/]+)\/(?P<restart_count>\d+)\.log$
              type: regex_parser
            - from: attributes.log
              to: body
              type: move
            - from: attributes.stream
              to: attributes["log.iostream"]
              type: move
            - from: attributes.container_name
              to: resource["k8s.container.name"]
              type: move
            - from: attributes.namespace
              to: resource["k8s.namespace.name"]
              type: move
            - from: attributes.pod_name
              to: resource["k8s.pod.name"]
              type: move
            - from: attributes.restart_count
              to: resource["k8s.container.restart_count"]
              type: move
            - from: attributes.uid
              to: resource["k8s.pod.uid"]
              type: move
        start_at: end
exporters:
    logging/debug:
        verbosity: detailed
    otlp/collector_otlp-test-output:
        endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
        tls:
            insecure: true
    otlp/collector_otlp-test-output-2:
        endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
        tls:
            insecure: true
processors:
    attributes/tenant_tenant-1:
        actions:
            - action: insert
              key: tenant_name
              value: tenant-1
    attributes/tenant_tenant-2:
        actions:
            - action: insert
              key: tenant_name
              value: tenant-2
    k8sattributes:
        auth_type: serviceAccount
        extract:
            labels:
                - from: pod
                  key_regex: .*
                  tag_name: all_labels
            metadata:
                - k8s.pod.name
                - k8s.pod.uid
                - k8s.deployment.name
                - k8s.namespace.name
                - k8s.node.name
                - k8s.pod.start_time
        passthrough: false
        pod_association:
            - sources:
                - name: k8s.namespace.name
                  from: resource_attribute
                - name: k8s.pod.name
                  from: resource_attribute
        connectors:
            routing/subscription_example-tenant-ns_subscription-example-1_outputs:
                table:
                    - statement: route()
                      pipelines: [logs/output_example-tenant-ns_subscription-example-1_collector_loki-test-output, logs/output_example-tenant-ns_subscription-example-1_collector_otlp-test-output]
            routing/subscription_example-tenant-ns_subscription-example-2_outputs:
                table:
                    - statement: route()
                      pipelines: [logs/output_example-tenant-ns_subscription-example-2_collector_otlp-test-output-2]
            routing/tenant_example-tenant_subscriptions:
                table:
                    - statement: route()
                      pipelines: [logs/tenant_example-tenant_subscription_example-tenant-ns_subscription-example-1]
                    - statement: 'route() '
                      pipelines: [logs/tenant_example-tenant_subscription_example-tenant-ns_subscription-example-2]
            routing/tenants:
                table:
                    - statement: 'route() where '
                      pipelines: [logs/tenant_example-tenant]
service:
    pipelines:
        logs/all:
            receivers: [filelog/kubernetes]
            processors: [k8sattributes]
            exporters: [routing/tenants]
        logs/tenant_tenant-1:
            receivers: [routing/tenants]
            processors: [attributes/tenant_tenant-1]
            exporters: [routing/tenant_tenant-1_subscriptions]
        logs/tenant_tenant-2:
            receivers: [routing/tenants]
            processors: [attributes/tenant_tenant-2]
            exporters: [routing/tenant_tenant-2_subscriptions]
        logs/tenant_tenant-1_subscription_subscription-example-1:
            receivers: [routing/tenant_tenant-1_subscriptions]
            processors: [attributes/subscription_subscription-example-1]
            exporters: [otlp/collector_otlp-test-output-1]
        logs/tenant_tenant-2_subscription_subscription-example-2:
            receivers: [routing/tenant_tenant-2_subscriptions]
            processors: [attributes/subscription_subscription-example-2]
            exporters: [otlp/collector_otlp-test-output-2]
