apiVersion: v1
kind: Namespace
metadata:
  name: collector
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tenant: es-demo
  name: tenant-es-demo
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: kubernetes
spec:
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collectorLabel: kubernetes
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collectorLabel: kubernetes
  name: es-demo
spec:
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: es-demo
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: es-demo
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: all-logs
  namespace: tenant-es-demo
spec:
  condition: "true"
  outputs:
    - name: elasticsearch
      namespace: tenant-es-demo
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: elasticsearch
  namespace: tenant-es-demo
spec:
  elasticsearch:
    endpoint: https://elasticsearch-master.elasticsearch.svc.cluster.local:9200
    tls:
      insecure_skip_verify: true
    mapping:
      mode: ecs
  authentication:
    basicAuth:
      secretRef:
        name: elasticsearch-master-credentials
        namespace: elasticsearch
      usernameField: username
      passwordField: password
