apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
{{ include "telemetry-controller.labels" . | indent 4 }}
  name: {{ include "telemetry-controller.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.monitoring.secure }}
    - name: {{ .Values.service.https.name }}
      port: {{ .Values.service.https.port }}
      protocol: {{ .Values.service.https.protocol }}
      targetPort: {{ .Values.service.https.targetPort }}
    {{- else }}
    - name: {{ .Values.service.http.name }}
      port: {{ .Values.service.http.port }}
      protocol: {{ .Values.service.http.protocol }}
      targetPort: {{ .Values.service.http.targetPort }}
    {{- end }}
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ include "telemetry-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
