apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "telemetry-controller.labels" . | indent 4 }}
  name: '{{ include "telemetry-controller.fullname" . }}-metrics-service'
  namespace: "{{.Release.Namespace}}"
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "telemetry-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
