apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "telemetry-controller.labels" . | indent 4 }}
  name: '{{ include "telemetry-controller.serviceAccountName" . }}'
  namespace: "{{.Release.Namespace}}"
