apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: telemetry-controller
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: telemetry-controller
    control-plane: controller-manager
  name: '{{ include "telemetry-controller.fullname" . }}-metrics-service'
  namespace: "{{.Release.Namespace}}"
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "telemetry-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
