apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "telemetry-controller.labels" . | indent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  name: '{{ include "telemetry-controller.serviceAccountName" . }}'
  namespace: "{{.Release.Namespace}}"
